server:
  host: localhost

spring:
  mvc:
    log-resolved-exception: true

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  datasource:
    url: jdbc:h2:~/app
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      platform: h2
      mode: always
      data-locations: classpath*:data/data-h2.sql

access_token_private_key_path: "access-refresh-token-keys/access-token-private.key"
access_token_public_key_path: "access-refresh-token-keys/access-token-public.key"
refresh_token_private_key_path: "access-refresh-token-keys/refresh-token-private.key"
refresh_token_public_key_path: "access-refresh-token-keys/refresh-token-public.key"
